package climategen

var (
	climates = []string{
		"coniferous",
		"deciduous",
		"desert",
		"grassland",
		"marshland",
		"tropical",
		"mountain",
		"rainforest",
		"savanna",
		"steppe",
		"taiga",
		"tundra",
	}

	climateData = map[string]Climate{
		"coniferous": Climate{
			Name:        "coniferous forest",
			Temperature: 4,
			Humidity:    6,
			Resources: []string{
				"bears",
				"beavers",
				"berries",
				"chamois",
				"geese",
				"softwood",
			},
		},
		"deciduous": Climate{
			Name:        "deciduous forest",
			Temperature: 5,
			Humidity:    5,
			Resources: []string{
				"berries",
				"deer",
				"eagles",
				"hardwood",
				"herbs",
				"mushrooms",
				"squirrels",
				"wolves",
			},
		},
		"desert": Climate{
			Name:        "desert",
			Temperature: 9,
			Humidity:    0,
			Resources: []string{
				"camels",
				"copper",
				"glass",
				"gold",
				"iron",
				"oil",
				"salt",
				"scorpions",
				"silver",
				"turquoise",
			},
		},
		"grassland": Climate{
			Name:        "grassland",
			Temperature: 5,
			Humidity:    3,
			Resources: []string{
				"bison",
				"bobcats",
				"chickens",
				"coyotes",
				"flowers",
				"horses",
				"cattle",
			},
		},
		"marshland": Climate{
			Name:        "marshland",
			Temperature: 7,
			Humidity:    9,
			Resources: []string{
				"alligators",
				"ducks",
				"flamingos",
				"herbs",
				"reeds",
				"vines",
			},
		},
		"tropical": Climate{
			Name:        "tropical",
			Temperature: 9,
			Humidity:    7,
			Resources: []string{
				"avocados",
				"bananas",
				"coconuts",
				"coffee",
				"elephants",
				"jaguars",
				"mangos",
				"pineapples",
				"tigers",
				"yams",
			},
		},
		"mountain": Climate{
			Name:        "mountain",
			Temperature: 4,
			Humidity:    4,
			Resources: []string{
				"coal",
				"copper",
				"diamonds",
				"gold",
				"granite",
				"iron",
				"limestone",
				"marble",
				"sandstone",
				"silver",
			},
		},
		"rainforest": Climate{
			Name:        "rainforest",
			Temperature: 9,
			Humidity:    9,
			Resources: []string{
				"avocados",
				"bananas",
				"coconuts",
				"flowers",
				"hardwood",
				"herbs",
				"mushrooms",
				"pineapples",
				"softwood",
				"yams",
			},
		},
		"savanna": Climate{
			Name:        "savanna",
			Temperature: 9,
			Humidity:    5,
			Resources: []string{
				"cheetahs",
				"copper",
				"diamonds",
				"elephants",
				"gazelles",
				"gold",
				"hippos",
				"lions",
				"nickel",
				"rubies",
				"sapphires",
				"silver",
				"zebras",
			},
		},
		"steppe": Climate{
			Name:        "steppe",
			Temperature: 7,
			Humidity:    3,
			Resources: []string{
				"antelopes",
				"donkeys",
				"flowers",
				"horses",
				"meerkats",
				"rabbits",
				"sheep",
				"tea",
				"wolves",
			},
		},
		"taiga": Climate{
			Name:        "taiga",
			Temperature: 3,
			Humidity:    3,
			Resources: []string{
				"ermines",
				"foxes",
				"iron",
				"minks",
				"oil",
				"rabbits",
				"salmon",
				"squirrels",
				"trout",
				"wolves",
			},
		},
		"tundra": Climate{
			Name:        "tundra",
			Temperature: 1,
			Humidity:    3,
			Resources: []string{
				"coal",
				"cod",
				"copper",
				"falcons",
				"iron",
				"nickel",
				"oil",
				"rabbits",
				"reindeer",
				"trout",
			},
		},
	}
)
