package climategen

var (
	climates = []string{
		"coniferous",
		"deciduous",
		"desert",
		"grassland",
		"marshland",
		"tropical",
		"mountain",
		"rainforest",
		"savanna",
		"steppe",
		"taiga",
		"tundra",
	}

	climateData = map[string]Climate{
		"coniferous": Climate{
			Name:        "coniferous forest",
			Temperature: 4,
			Humidity:    6,
			Resources: []string{
				"bear pelts",
				"beaver pelts",
				"berries",
				"chamois",
				"geese",
				"softwood",
			},
		},
		"deciduous": Climate{
			Name:        "deciduous forest",
			Temperature: 5,
			Humidity:    5,
			Resources: []string{
				"berries",
				"venison",
				"eagle feathers",
				"hardwood",
				"herbs",
				"mushrooms",
				"squirrel hides",
				"wolf pelts",
			},
		},
		"desert": Climate{
			Name:        "desert",
			Temperature: 9,
			Humidity:    0,
			Resources: []string{
				"camels",
				"copper",
				"glass",
				"gold",
				"iron",
				"oil",
				"salt",
				"scorpion venom",
				"silver",
				"turquoise",
			},
		},
		"grassland": Climate{
			Name:        "grassland",
			Temperature: 5,
			Humidity:    3,
			Resources: []string{
				"bison meat",
				"bison hides",
				"bobcat hides",
				"chickens",
				"coyote pelts",
				"flowers",
				"horses",
				"cattle",
			},
		},
		"marshland": Climate{
			Name:        "marshland",
			Temperature: 7,
			Humidity:    9,
			Resources: []string{
				"alligator hides",
				"ducks",
				"flamingo feathers",
				"snakeskin",
				"herbs",
				"reeds",
				"vines",
			},
		},
		"tropical": Climate{
			Name:        "tropical",
			Temperature: 9,
			Humidity:    7,
			Resources: []string{
				"avocados",
				"bananas",
				"coconuts",
				"coffee",
				"elephant hides",
				"ivory",
				"jaguar pelts",
				"mangos",
				"pineapples",
				"tiger pelts",
				"yams",
			},
		},
		"mountain": Climate{
			Name:        "mountain",
			Temperature: 4,
			Humidity:    4,
			Resources: []string{
				"coal",
				"copper",
				"diamonds",
				"gold",
				"granite",
				"iron",
				"limestone",
				"marble",
				"sandstone",
				"silver",
			},
		},
		"rainforest": Climate{
			Name:        "rainforest",
			Temperature: 9,
			Humidity:    9,
			Resources: []string{
				"avocados",
				"bananas",
				"coconuts",
				"flowers",
				"hardwood",
				"herbs",
				"mushrooms",
				"pineapples",
				"softwood",
				"yams",
			},
		},
		"savanna": Climate{
			Name:        "savanna",
			Temperature: 9,
			Humidity:    5,
			Resources: []string{
				"cheetah hides",
				"copper",
				"diamonds",
				"elephant hides",
				"ivory",
				"gazelle hides",
				"gold",
				"hippo hides",
				"lions",
				"nickel",
				"rubies",
				"sapphires",
				"silver",
				"zebra hides",
			},
		},
		"steppe": Climate{
			Name:        "steppe",
			Temperature: 7,
			Humidity:    3,
			Resources: []string{
				"antelope meat",
				"donkeys",
				"flowers",
				"horses",
				"rabbit hides",
				"sheep",
				"wool",
				"lamb",
				"tea",
				"wolf pelts",
			},
		},
		"taiga": Climate{
			Name:        "taiga",
			Temperature: 3,
			Humidity:    3,
			Resources: []string{
				"ermine pelts",
				"fox hides",
				"iron",
				"mink pelts",
				"oil",
				"rabbit hides",
				"salmon",
				"squirrel hides",
				"trout",
				"wolf pelts",
			},
		},
		"tundra": Climate{
			Name:        "tundra",
			Temperature: 1,
			Humidity:    3,
			Resources: []string{
				"coal",
				"cod",
				"copper",
				"falcons",
				"iron",
				"nickel",
				"oil",
				"rabbit hides",
				"reindeer meat",
				"reindeer hides",
				"trout",
			},
		},
	}
)
